export const LOCATION_ACTIONS = {
	FETCH_LOCATIONS_REQUEST: 'FETCH_LOCATIONS_REQUEST',
	FETCH_LOCATIONS_SUCCESS: 'FETCH_LOCATIONS_SUCCESS',
	// FETCH_LOCATIONS_FAILED: 'FETCH_LOCATIONS_FAILED',
	CHANGE_LOCATION_SELECT: 'CHANGE_LOCATION_SELECT',
};
